# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Idaho Waters Digital Library
# Scientific and technical reports, with an emphasis on Idaho Water Resources Research Institute reports and publications
tagline: "A collection of scientific and technical reports relating to water issues in key Idaho river basins" 
description: "A collection of scientific and technical reports relating to water issues in key Idaho river basins" 
keywords: university of idaho, Idaho Water Resources Research Institute, Idaho, water resources
email: ewilliamson@uidaho.edu

# url variables
url: https://www.lib.uidaho.edu
baseurl: /digital/iwdl
liburl: https://www.lib.uidaho.edu
digurl: https://www.lib.uidaho.edu/digital
repourl: https://digital.lib.uidaho.edu

# Dev variables: 
# choose metadata set, i.e. easily switch between full or dev version
metadata: iwdl-dev

# collection display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'iwdl'
    template: 'docs'
    name: 'resource-identifier'
    dir: 'docs'
    extension: 'html'

# data fields: 
# title,creator,date,location,lat-long,subject,description,collection,series,related-dataset,contributors,publisher,contributing-institution,language,iwrri-number,resource-identifier,rights,rights-standardized,format,type,date-digital,digitization-specifications,metadata-cataloger,filename,cdm-number
